//package com.presenz.app.ble
//
//import java.nio.charset.StandardCharsets
//
///**
// * presenZ BLE wire protocol.
// *
// * We piggy-back on BLE "manufacturer specific data" advertising fields instead
// * of opening a GATT connection - this keeps things fast/simple and works
// * purely as connectionless broadcast + scan, which is all an MVP needs.
// *
// * Packet layout (bytes), after the 2-byte manufacturer company ID:
// *   [0]      -> packet type (TYPE_SESSION or TYPE_STUDENT_RESPONSE)
// *   TYPE_SESSION:
// *     [1..6] -> 6-char session token (ASCII)
// *   TYPE_STUDENT_RESPONSE:
// *     [1..6]  -> 6-char session token being echoed back (ASCII)
// *     [7..]   -> roll number (ASCII, up to MAX_ROLLNO_LEN chars)
// *
// * Advertising packets are small (legacy BLE ~31 bytes total), so we keep
// * this payload deliberately compact.
// */
//object BleProtocol {
//
//    // Not an officially registered Bluetooth SIG company ID - fine for a
//    // local/offline MVP. If you plan to ship this, request a real one.
//    const val MANUFACTURER_ID = 0x5A11 // "presenZ"
//
//    const val TYPE_SESSION: Byte = 0x01
//    const val TYPE_STUDENT_RESPONSE: Byte = 0x02
//
//    const val TOKEN_LEN = 6
//    const val MAX_ROLLNO_LEN = 14
//
//    fun encodeSessionPayload(token: String): ByteArray {
//        val t = token.uppercase().padEnd(TOKEN_LEN, 'X').take(TOKEN_LEN)
//        val out = ByteArray(1 + TOKEN_LEN)
//        out[0] = TYPE_SESSION
//        t.toByteArray(StandardCharsets.US_ASCII).copyInto(out, 1)
//        return out
//    }
//
//    fun encodeStudentPayload(token: String, rollNo: String): ByteArray {
//        val t = token.uppercase().padEnd(TOKEN_LEN, 'X').take(TOKEN_LEN)
//        val r = rollNo.uppercase().take(MAX_ROLLNO_LEN)
//        val rBytes = r.toByteArray(StandardCharsets.US_ASCII)
//        val out = ByteArray(1 + TOKEN_LEN + rBytes.size)
//        out[0] = TYPE_STUDENT_RESPONSE
//        t.toByteArray(StandardCharsets.US_ASCII).copyInto(out, 1)
//        rBytes.copyInto(out, 1 + TOKEN_LEN)
//        return out
//    }
//
//    data class SessionAdvert(val token: String)
//    data class StudentAdvert(val token: String, val rollNo: String)
//
//    fun decodeSession(data: ByteArray): SessionAdvert? {
//        if (data.isEmpty() || data[0] != TYPE_SESSION) return null
//        if (data.size < 1 + TOKEN_LEN) return null
//        val token = String(data, 1, TOKEN_LEN, StandardCharsets.US_ASCII)
//        return SessionAdvert(token)
//    }
//
//    fun decodeStudent(data: ByteArray): StudentAdvert? {
//        if (data.isEmpty() || data[0] != TYPE_STUDENT_RESPONSE) return null
//        if (data.size < 1 + TOKEN_LEN) return null
//        val token = String(data, 1, TOKEN_LEN, StandardCharsets.US_ASCII)
//        val rollNoLen = data.size - 1 - TOKEN_LEN
//        if (rollNoLen <= 0) return null
//        val rollNo = String(data, 1 + TOKEN_LEN, rollNoLen, StandardCharsets.US_ASCII)
//        return StudentAdvert(token, rollNo)
//    }
//}

package com.presenz.app.ble

import java.nio.charset.StandardCharsets

/**
 * presenZ BLE wire protocol.
 *
 * We use BLE manufacturer-specific advertising data.
 *
 * Packet layout:
 *
 * SESSION:
 *
 *   [0]       packet type
 *   [1..6]    6-character session token
 *   [7..]     group code
 *
 *
 * STUDENT RESPONSE:
 *
 *   [0]       packet type
 *   [1..6]    6-character session token
 *   [7..]     roll number
 *
 *
 * Example:
 *
 * SESSION:
 *   01 | ABC123 | CSEA
 *
 * STUDENT:
 *   02 | ABC123 | 24CSE001
 */
object BleProtocol {

    /*
     * Local/private manufacturer ID used by presenZ.
     */
    const val MANUFACTURER_ID = 0x5A11

    const val TYPE_SESSION: Byte = 0x01
    const val TYPE_STUDENT_RESPONSE: Byte = 0x02

    /*
     * Session token generated by backend.
     */
    const val TOKEN_LEN = 6

    /*
     * Keep these values deliberately small because
     * legacy BLE advertising packets have limited space.
     */
    const val MAX_GROUP_CODE_LEN = 8
    const val MAX_ROLLNO_LEN = 14


    // ---------------------------------------------------------------------
    // SESSION ADVERTISEMENT
    // ---------------------------------------------------------------------

    /**
     * Creates:
     *
     * [TYPE_SESSION][TOKEN][GROUP_CODE]
     */
    fun encodeSessionPayload(
        token: String,
        groupCode: String
    ): ByteArray {

        val normalizedToken =
            token
                .uppercase()
                .padEnd(TOKEN_LEN, 'X')
                .take(TOKEN_LEN)

        val normalizedGroup =
            groupCode
                .uppercase()
                .trim()
                .take(MAX_GROUP_CODE_LEN)

        val tokenBytes =
            normalizedToken.toByteArray(
                StandardCharsets.US_ASCII
            )

        val groupBytes =
            normalizedGroup.toByteArray(
                StandardCharsets.US_ASCII
            )

        val out =
            ByteArray(
                1 +
                        TOKEN_LEN +
                        groupBytes.size
            )

        out[0] = TYPE_SESSION

        tokenBytes.copyInto(
            out,
            destinationOffset = 1
        )

        groupBytes.copyInto(
            out,
            destinationOffset = 1 + TOKEN_LEN
        )

        return out
    }


    // ---------------------------------------------------------------------
    // STUDENT RESPONSE
    // ---------------------------------------------------------------------

    /**
     * Creates:
     *
     * [TYPE_STUDENT_RESPONSE][TOKEN][ROLL_NO]
     */
    fun encodeStudentPayload(
        token: String,
        rollNo: String,
        groupCode:String
    ): ByteArray {

        val normalizedToken =
            token
                .uppercase()
                .padEnd(TOKEN_LEN, 'X')
                .take(TOKEN_LEN)

        val normalizedRollNo =
            rollNo
                .uppercase()
                .trim()
                .take(MAX_ROLLNO_LEN)

        val tokenBytes =
            normalizedToken.toByteArray(
                StandardCharsets.US_ASCII
            )

        val rollNoBytes =
            normalizedRollNo.toByteArray(
                StandardCharsets.US_ASCII
            )

        val out =
            ByteArray(
                1 +
                        TOKEN_LEN +
                        rollNoBytes.size
            )

        out[0] = TYPE_STUDENT_RESPONSE

        tokenBytes.copyInto(
            out,
            destinationOffset = 1
        )

        rollNoBytes.copyInto(
            out,
            destinationOffset = 1 + TOKEN_LEN
        )

        return out
    }


    // ---------------------------------------------------------------------
    // DECODE MODELS
    // ---------------------------------------------------------------------

    data class SessionAdvert(
        val token: String,
        val groupCode: String
    )

    data class StudentAdvert(
        val token: String,
        val rollNo: String
    )


    // ---------------------------------------------------------------------
    // DECODE SESSION
    // ---------------------------------------------------------------------

    fun decodeSession(
        data: ByteArray
    ): SessionAdvert? {

        /*
         * Minimum:
         *
         * 1 byte type
         * 6 bytes token
         * 1 byte group code
         */
        if (
            data.size <
            1 + TOKEN_LEN + 1
        ) {
            return null
        }

        if (
            data[0] != TYPE_SESSION
        ) {
            return null
        }

        val token =
            String(
                data,
                1,
                TOKEN_LEN,
                StandardCharsets.US_ASCII
            )

        val groupCodeLength =
            data.size - 1 - TOKEN_LEN

        if (groupCodeLength <= 0) {
            return null
        }

        val groupCode =
            String(
                data,
                1 + TOKEN_LEN,
                groupCodeLength,
                StandardCharsets.US_ASCII
            )
                .trim()
                .uppercase()

        if (groupCode.isEmpty()) {
            return null
        }

        return SessionAdvert(
            token = token,
            groupCode = groupCode
        )
    }


    // ---------------------------------------------------------------------
    // DECODE STUDENT
    // ---------------------------------------------------------------------

    fun decodeStudent(
        data: ByteArray
    ): StudentAdvert? {

        /*
         * Minimum:
         *
         * 1 byte type
         * 6 bytes token
         * at least 1 byte roll number
         */
        if (
            data.size <
            1 + TOKEN_LEN + 1
        ) {
            return null
        }

        if (
            data[0] != TYPE_STUDENT_RESPONSE
        ) {
            return null
        }

        val token =
            String(
                data,
                1,
                TOKEN_LEN,
                StandardCharsets.US_ASCII
            )

        val rollNoLength =
            data.size - 1 - TOKEN_LEN

        if (rollNoLength <= 0) {
            return null
        }

        val rollNo =
            String(
                data,
                1 + TOKEN_LEN,
                rollNoLength,
                StandardCharsets.US_ASCII
            )
                .trim()
                .uppercase()

        if (rollNo.isEmpty()) {
            return null
        }

        return StudentAdvert(
            token = token,
            rollNo = rollNo
        )
    }
}